os:
  - linux

sudo: false

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid

# safelist
branches:
  only:
  - master

git:
  # We rely on git tags for determining the version.
  depth: false

cache:
  bundler: true
  directories:
    - $HOME/.pub-cache

# Testing
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - ./flutter/bin/flutter doctor -v
  - ./flutter/bin/flutter packages get
  - gem install coveralls-lcov

script:
  - ulimit -S -n 2048
  - ./flutter/bin/flutter analyze lib/ test/
  - ./flutter/bin/flutter test --coverage

after_script:
  - coveralls-lcov coverage/lcov.info

after_success:
  - ./ci/setup.sh 
  - ./ci/build.sh
