os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - lib32stdc++6
      - libstdc++6
      - fonts-droid
before_script:
  - ./ci/setup.sh
script:
  - ./ci/lint.sh
  - ./ci/deploy.sh
cache:
  directories:
    - $HOME/.pub-cache
